### ISSUE TITLE
change xrange for range

### ISSUE THREAD

**Issue by di0nys0s** [nzhagen/jcamp#7]
On line 255 and 256 of jcamp.py :
            bool = list(True for i in xrange(0,len(s)))
            for i in xrange(0,len(s)):

must be :
            bool = list(True for i in range(0,len(s)))
            for i in range(0,len(s)):

to run on python 3.4

**Comment by nzhagen** [comment]
Glad you mentioned that. I originally had "range" but a collaborator
changed it to "xrange" because that's what a lot of online info says you
should do. But I think it's unnecessary here, and you pointed out that it
breaks compatibility with Python3. I've uploaded the change. Thanks for the
suggestion!

- Nathan
